# Generated by Django 5.2.7 on 2026-02-04 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="album_covers/"),
                ),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playlist_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="songs/")),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("mime_type", models.CharField(max_length=50)),
                ("is_uploaded_to_cloud", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploadedSongs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playlist_song_uuid",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("order", models.IntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.playlist"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.song"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["artist_uuid"], name="music_artis_artist__16088d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="music_artis_name_e97718_idx"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["created_by"], name="music_artis_created_e7c3fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["album_uuid"], name="music_album_album_u_5c4f08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist"], name="music_album_artist__0d9e80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["title"], name="music_album_title_ddf06b_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["created_by"], name="music_album_created_d16332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["playlist_uuid"], name="music_playl_playlis_d06c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["owner"], name="music_playl_owner_i_62b86b_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["song_uuid"], name="music_song_song_uu_6a2354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["artist"], name="music_song_artist__c5a493_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["album"], name="music_song_album_i_36c1e6_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["uploaded_by"], name="music_song_uploade_616c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistsong",
            index=models.Index(
                fields=["playlist_song_uuid"], name="music_playl_playlis_1c5a07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistsong",
            index=models.Index(
                fields=["playlist", "order"], name="music_playl_playlis_89a078_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistsong",
            unique_together={("playlist", "song")},
        ),
    ]
