# Generated by Django 5.2.7 on 2026-01-31 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "coverImage",
                    models.ImageField(blank=True, null=True, upload_to="album_covers/"),
                ),
                ("releaseYear", models.IntegerField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playlist_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="songs/")),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in seconds"),
                ),
                ("size", models.PositiveBigIntegerField()),
                ("mimeType", models.CharField(max_length=50)),
                ("isPublic", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.artist"
                    ),
                ),
                (
                    "uploadedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploadedSongs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("addedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.playlist"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.song"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["artist_uuid"], name="music_artis_artist__16088d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="music_artis_name_e97718_idx"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                fields=["createdBy"], name="music_artis_created_ec84c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["album_uuid"], name="music_album_album_u_5c4f08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist"], name="music_album_artist__0d9e80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["title"], name="music_album_title_ddf06b_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["createdBy"], name="music_album_created_fa67d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["playlist_uuid"], name="music_playl_playlis_d06c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["owner"], name="music_playl_owner_i_62b86b_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["song_uuid"], name="music_song_song_uu_6a2354_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["artist"], name="music_song_artist__c5a493_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["album"], name="music_song_album_i_36c1e6_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["uploadedBy"], name="music_song_uploade_a41d38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistsong",
            index=models.Index(
                fields=["playlist", "order"], name="music_playl_playlis_89a078_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistsong",
            unique_together={("playlist", "song")},
        ),
    ]
