# Generated by Django 5.2.7 on 2026-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_song_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_upload_complete",
            field=models.BooleanField(default=False),
        ),
    ]
