# Generated by Django 5.2.7 on 2026-02-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_song_is_upload_complete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="playlist",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ["title"]},
        ),
    ]
