# Generated by Django 5.2.7 on 2026-03-24 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_album_options_alter_artist_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SharedPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_links",
                        to="music.playlist",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
                "indexes": [
                    models.Index(
                        fields=["playlist"], name="music_share_playlis_a3e1bf_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("playlist",), name="unique_shared_playlist"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_links",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
                "indexes": [
                    models.Index(fields=["song"], name="music_share_song_id_e95ad3_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("song",), name="unique_shared_song")
                ],
            },
        ),
    ]
