# Generated by Django 5.2.7 on 2026-03-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_playlist_is_public_sharedplaylist_sharedsong"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="album",
            name="music_album_album_u_5c4f08_idx",
        ),
        migrations.RemoveIndex(
            model_name="artist",
            name="music_artis_artist__16088d_idx",
        ),
        migrations.RemoveIndex(
            model_name="playlist",
            name="music_playl_playlis_d06c7b_idx",
        ),
        migrations.RemoveIndex(
            model_name="playlistsong",
            name="music_playl_playlis_1c5a07_idx",
        ),
        migrations.RemoveIndex(
            model_name="song",
            name="music_song_song_uu_6a2354_idx",
        ),
    ]
