# Generated by Django 5.2.7 on 2026-04-05 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0006_remove_album_music_album_album_u_5c4f08_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sharedplaylist",
            name="music_share_playlis_a3e1bf_idx",
        ),
        migrations.RemoveIndex(
            model_name="sharedsong",
            name="music_share_song_id_e95ad3_idx",
        ),
        migrations.RemoveIndex(
            model_name="song",
            name="music_song_uploade_616c47_idx",
        ),
        migrations.AddIndex(
            model_name="playlistsong",
            index=models.Index(fields=["song"], name="music_playl_song_id_d008b7_idx"),
        ),
        migrations.AddIndex(
            model_name="sharedplaylist",
            index=models.Index(
                fields=["playlist", "shared_by"], name="music_share_playlis_3f09f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedsong",
            index=models.Index(
                fields=["song", "shared_by"], name="music_share_song_id_2c1666_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["uploaded_by", "is_uploaded_to_cloud", "is_upload_complete"],
                name="music_song_uploade_49f307_idx",
            ),
        ),
    ]
